@host = http://localhost:8080
@defaultUserId = sampleUser1
@defaultPassword = Passw0rd!
@defaultNewPassword = Passw0rd!2

### 사용자 회원가입
# @name signUp
POST {{host}}/users/sign-up
Content-Type: application/json

{
  "userId": "{{defaultUserId}}",
  "password": "{{defaultPassword}}",
  "name": "샘플 사용자",
  "email": "sample@example.com",
  "phone": "010-0000-0000",
  "address": "서울시 어딘가",
  "nickName": "샘플닉네임",
  "status": "DEFAULT"
}

### 로그인 (세션 쿠키 저장)
# @name login
POST {{host}}/users/login
Content-Type: application/json

{
  "userId": "{{defaultUserId}}",
  "password": "{{defaultPassword}}"
}

### 내 정보 조회 (로그인 필요)
# @name myInfo
GET {{host}}/users/my-info

### 비밀번호 변경 (로그인 필요)
# @name changePassword
PATCH {{host}}/users/password
Content-Type: application/json

{
  "currentPassword": "{{defaultPassword}}",
  "newPassword": "{{defaultNewPassword}}"
}

### 로그아웃 (세션 제거)
# @name logout
POST {{host}}/users/logout

### 회원 탈퇴 (로그인 필요)
# @name deleteUser
DELETE {{host}}/users/delete
Content-Type: application/json

{
  "password": "{{defaultNewPassword}}"
}
